forge "http://forge.puppetlabs.com"

mod "puppetlabs/apt", ">=0.0.3"

mod "puppetlabs/stdlib", ">=2.0.0"

mod "puppetlabs/nodejs", ">=0.3.0"


# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
